### ISSUE TITLE
Core: implement @recurse directive

### ISSUE THREAD

**Issue by snipebin** [binier/dgraphium#13]
Implement Dgraph's [@recurse](https://dgraph.io/docs/query-language/recurse-query/) directive.

**Comment by snipebin** [comment]
@binier I want to implement this, would be great to have some guidance. Here's what I'm thinking

1.  Add recurse to the edge interface like cascade, the args will be scalars that the @recurse query optionally accepts:  `@recurse(depth: 5, loop: true)`
2. Will add recurse to [DirectiveArgs](https://github.com/binier/dgraphium/blob/7fc61391ce56949616570684bcbab1f3a53369f8/packages/core/src/directive/directive.ts#L4) and [DirectiveBuilderArgs](https://github.com/binier/dgraphium/blob/1539efebc0a4829f3406a3e45b23a43f662bdc10/packages/core/src/directive/directive-builder.ts#L6)
3. Implement an arg type for recurse that can out put key value pairs, i.e. `depth: 5, loop: true`. Probably best to be something generic, as there are other functions/directives which expects this format for arguments, i.e. [shortest path](https://dgraph.io/docs/query-language/kshortest-path-quries/)
3.1 This format is already used in [args implementation](https://github.com/binier/dgraphium/blob/1539efebc0a4829f3406a3e45b23a43f662bdc10/packages/core/src/args/args.ts#L35) powering search criteria (`func: ...`), sorting and pagination, but it's tightly coupled. Should I refactor that to use the new generic component?

Let me know if this sounds good or if you're thinking a completely different design that's fine too

**Comment by binier** [comment]
@snipebin Thanks for willing to contribute. If you'll have any more questions feel free to ask them.

**1,2,3.** Just make args of type `{ depth: number, loop: boolean }` then you can modify `Directive.toString()` to convert that object to string. Also not sure if `@recurse` directive can be used on edge, if it can - implement `EdgeBuilder.recurse(depth, loop)` method, otherwise - `QueryBuilder.recurse(depth, loop)`.

**4.** I know it's a bit confusing... Basically Most of the builder's build logic is seperated from the builder. So **EdgeBuilder** is basically in charge of building any nested builders it contains. I did that to avoid repetition in different builders since each builder might contain nested builder. Might not be the best design and most likely there is better way to do this, it's just that initially I wanted maximum flexibility since I didn't have in depth knowledge of Dgraph and didn't want to be refactoring all the time. Maybe after this project supports all or most of the features, we can refactor that.
